// notification.js
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_ERROR = 'SET_ERROR';
export const SET_MESSAGE_CLEARING_TIMEOUT_ID =
  'SET_MESSAGE_CLEARING_TIMEOUT_ID';
export const SET_ERROR_CLEARING_TIMEOUT_ID = 'SET_ERROR_CLEARING_TIMEOUT_ID';

// auth.js
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_REFRESH_INTERVAL_ID = 'SET_REFRESH_INTERVAL_ID';
export const SET_AUTHENTICATING = 'SET_AUTHENTICATING';

// navigation.js
export const SET_SHOWED_DROPDOWN = 'SET_SHOWED_DROPDOWN';
export const ADD_TO_DROPDOWN = 'ADD_TO_DROPDOWN';
export const REMOVE_FROM_DROPDOWN = 'REMOVE_FROM_DROPDOWN';
